name: langvider
description: A new Flutter application.
version: 0.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  
  pedantic: ^1.8.0

  provider: ^4.0.4

  dio: 3.0.4

  # Firebase
  firebase_core: 0.4.0+9
  firebase_auth: 0.14.0+5
  cloud_firestore: 0.12.9+5
  google_sign_in: 4.0.7

  google_fonts: ^0.3.9

  logger: ^0.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/assets/google_fonts/